name: tagpr

on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}

      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
